# This file is used to define the properties of the filesystem
# images generated by build tools (mkbootfs and mkyaffs2image) and
# by the device side of adb.

[AID_VENDOR_QCOM_DIAG]
value:2950

# [system/bin/qmuxd]
# mode: 0755
# user: AID_SYSTEM
# group: AID_SYSTEM
# caps: WAKE_ALARM
