# Sensors
SOMC_CFG_SENSORS := true
SOMC_CFG_SENSORS_ACCEL_BMA250NA_INPUT := yes
SOMC_CFG_SENSORS_COMPASS_AK8963 := yes
SOMC_CFG_SENSORS_GYRO_MPU3050 := yes
SOMC_CFG_SENSORS_LIGHT_LM3533 := yes
SOMC_CFG_SENSORS_LIGHT_LM3533_PATH := "/sys/bus/i2c/devices/0-0036"
SOMC_CFG_SENSORS_LIGHT_MAXRANGE := 1530
SOMC_CFG_SENSORS_PROXIMITY_APDS9702 := yes
